runtime: python37
instance_class: F1
entrypoint: gunicorn -b :$PORT -w 2 -k uvicorn.workers.UvicornWorker main:app

handlers:
- url: /api/.*
  script: auto
- url: /static
  static_dir: static
- url: /logo
  static_dir: logo
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
- url: /.*
  static_files: index.html
  upload: index.html
